### ISSUE TITLE
please add my key

### ISSUE THREAD

**Issue by Justin-Wheaton** [mzbat/iac_workshop#12]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDerEhtIFmkMSii4Cq7bjf2b2I9jtRXP0w3tN9I9k1wKhWpsY3XdojvkBiSilartY8BdL4x8XOEeSqHpmgX6p8OMsWwxbXQ51ZFm3VfPsZe3RsDvcUKBJcHxnk0fqXAcYHXyIEys5XkYPhwitYAru2L/Rwr2IkKQW8VXx1tQ9v47NxEUAy6+up9V8Z7oofuws4meWdjL+iQGnCDqhrqjdMPyTppI2wTxWO+QqpaY/UxLoJuvEA0mQf3AJAiCZDVcxqPUfoGH+lbnFwsSQJi/0KFLevBRwGI1DrYQVhOP36Esr2TI60l0h36lDe0HIPMbMafbwNJsuhNre5BL0IcXI9P Justin@Justins-MacBook-Pro-2.local

**Comment by theDevilsVoice** [comment]
Thanks!

Added with username justin.

Should be able to log in a bit later today (after next PR is merged).
