### ISSUE TITLE
please add my key

### ISSUE THREAD

**Issue by nitsud33** [mzbat/iac_workshop#14]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDc4ap1CAZkvF8i9luHW8kakNwHN6HYECSWDtAmshc1BhaomUjeXu3jlq/05+0Azad4y5jG0SVs339XUz1TFDeWeeIooFikAvG3weSpRlC4beQS0gA+L2LNXRLoTXSD1qjwlc5fUBcTJIYhvIm/uSKG4qTuSNlCJEDVsqOpNkbtlqdrvGGw45+dcreDKqLP1IDfkRz7ROCB13mNZC+Feq0j8CVnOtDJUfxC4faDGX+1bmZOeiuz1X88VEAZk29iRv+dAbUoC07KliVErFFFDAAcmTrJXJ5hOnHiYBtNtqWKOZzqoINcIqOa4bEHKBUTWFpw+DNz7C1uB/fSuxUz4UVn dustinbixler@Dustins-MacBook-Pro.local
  
dbixler as a user name, thanks

**Comment by theDevilsVoice** [comment]
Thanks!

Added with username dustin

Should be able to log in a bit later today (after next PR is merged).
