### ISSUE TITLE
Please add my key

### ISSUE THREAD

**Issue by Atendam** [mzbat/iac_workshop#15]
Username: atendam

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC48PqsOVewfO1FofBxZiLq+7uFtBHDCrgUfogsZNepeBhI/LY66CCpafXBn0/Z1AWByGMStvJ/J126lBb+Jt42pja2z22VGNqPXxe7SB2v7VgMR8p1JskHJV6djMe9rY4H/74iWFyfKI07TYNqz9rOplVS/XKozBW+fL4q1xTeTJYCXgA6iSmMUyOGQVJSNoade2MUnX1enkP0rRAXdbhPUQbrV72AYEudeRY9R0jtbu4B4Wy4cxHm65LUKDoqiEPjFftCM085f+DD2qL3ef5ZklV0nKcvST3nb0MJ2MJbgv+VnludxjsqYUKeruDgu4cQVg8K3W5wribKOzVdPfV/jIkp0RwO+kePiFi1LJm7ZG+/xA5XYyVYzmUxeUDrZ7WRUEQBtpFHhNpoRw4e+tOUDqD4yIx8W3UXok3JEvuCCXNUEfkGHpLex6aR9pVvBpc78m0XYKKrr+es0vu98/7IqrJIFmRn5XEjtolfjGi3ReqYgDTplM0hlJcFEyAPuCHXE/Dd0TY6GTp2/q6OnlTv4JqjK7nQFWm7ZSQHkCdFh3xkNC3GlKmc24oo1qpLLMgA6l5dcjSh8+69d/grygn+tSvcEBVvQV1FToshqdNOELyJaAX7u7YDpPMf0d5ODcMzDirAPGZpmHwlkqG5U2ujLT1pAHOMPxrbC/Uh6ZyAJw== andrew.tendam@gmail.com

**Comment by theDevilsVoice** [comment]
Thanks!

Added with username andrew

Should be able to log in a bit later today (after next PR is merged).
