### ISSUE TITLE
Please add my key

### ISSUE THREAD

**Issue by jameskbride** [mzbat/iac_workshop#24]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7zL7rt0c4gdWE406j1e+NG1yYBHnyAtEIK86O0RUpOY9w744WM7/uf6qtN+dO/J+fYSINbpAxb8B2D9tciyBCGXmeLNCCD34ItEmvHhZV+18i+iyhkD8IXCutF/fhM9vyKMlMQ+ROieukGUTbvDMXzTRaOz1aImH5P7r3jCkOWiFVpunT/IF/OZvZQTHNjVYiyFnsBffMLNDc8B1lwdRiaR7RW+e5mRGnuYVcC9FExwbKEOik2ZENhqX8uSVmMNlnRxkgt57T/tGCfP+38SGke4zYKw6EQ/DpRJaZmAOKQduid3FZUBmV5q0UOWVx4skl6nC1qGR8aahq4vAnNCjj jameskbride@valhalla.local

Preferred username: jameskbride

**Comment by theDevilsVoice** [comment]
added
