### ISSUE TITLE
Please add my key

### ISSUE THREAD

**Issue by yamikuronue** [mzbat/iac_workshop#28]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLNIBUZ1VmJmM8gGDYXQn+WG9A0kURajhLMsCpqEgUiv5x9+ESD+VoUVRyz+zxxazLQ+5IakjfgxrcFn9COZrYl3zEvyTqd+jOB/09easzln+4n+o1J3kNDkvz+RFDSHXlMqR5DOb4w0n+E4IrXFiQFlHDksBrw/mQHsAmq0HgfanMQ24IktUmdk7E2jLJW02nbS//BYR2B5N+SU6XN0Ylc4DeRanbUajAWi/+W2gGbOlCiTgt5tZdQdPypnKsbHAmk+aCSeyUcK0K19yISx+LXivLKe6WtTAl6SlNKgLeUZ3woOfr6RQQFgoAd+3erIFvO4xnljZqPSleIs3LCjGsi2rSxH/EzMBawYd0CNhVi3CncNsT1pKDaZ6yIQXvkV/OT53IYbHE6LgsJXrxDd91AabQq2hlDUsju8m6Hhus+sV/cPlGUZIHycIHgMRheSUQCpZvo0E8ShshhhM6dIxIdfnuxgU3pLy0tti1LESDOoUl5AFPH4tSNlc4IAfwVsmWsl6FTwRtN2ZP4bt3ZormxZGJf6Tkf2i28m3MVQg4DExiaSPPi7tmuIN6GGco2yznvnPWvd1XFqV6K3sbHwOsr+QEUukYNrN1syRjQOUj2/Ivli17SUVRjip4xpgljYq6km7E6T1US4ZyjWJwFbdQOYgQSUAoVvQvZTkUZQ+LXw== yamikuronue@gmail.com

**Comment by theDevilsVoice** [comment]
username yamikurone

**Comment by yamikuronue** [comment]
spelled "yamikuronue" or "yamikurone"?
