### ISSUE TITLE
please add my key

### ISSUE THREAD

**Issue by zvercodebender** [mzbat/iac_workshop#31]

**Comment by zvercodebender** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0fBYDNGarDtTTOhNMpvDO7mcCPrV78X4KiYfYFY0N1MTe+yKKhNpRcFx/0irG0/64TXMadUJz5j0kXlVJuQsn+TwYRbRMKIinMysnPqf4l+4J2T9yIjUjfCZN9vv/CixANlaDB9KgQdsvXVg1EL+AsN2qnrl+AEXUZ1jAIV65FBQbmLfzsndrKw90qD2MOtn7UW62NAGD+bzADcJwisWpzq52TpKW/F5KgoL6ni8bW97IFNnWte9EUikgNq+RrfByiIAyCDw/MQ42yrFj96aKHeeZYnodX0aaCHcH/PY4y6EBl+i+mQ1uAaMMdul1LKs08EaX5jJb5+7NrLnsl6/n rick@goofy

**Comment by theDevilsVoice** [comment]
username zvercodebender
