### ISSUE TITLE
Please add my key

### ISSUE THREAD

**Issue by dvarmette** [mzbat/iac_workshop#32]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCa6O4Df2s/YMiT5iPZunJXJ0qqq5HIEt69JHwlI23C4H/1HDteX7iotsAGppuuc3EEVYpnzGkOlaplf9p7Ced88G3Yf+vBI1z2+J+brVTK4QZOODmzEcm7i0PrHXRfojapBsOLJwu5FJANxvyGaYfUMH4yAgzNnINRm8VepfOPnWqjvtlI4ufePwUVlkaEk59GZNZFaF7XldRCIJJO/d8fpC1L/rWqZzi66/62+gG9jD/9nHXMCJVJTGhbTDkW9/FBOceOG5zqXo8byFtDQK8PjTsNOWC+3E2P8wZjYkxi31rymI18/KcjXzU+iFP7rZ/Qx0hZNf/y5uTOob7qbPl dsvarmette@ra.rockwell.com

**Comment by theDevilsVoice** [comment]
username dsvarmette
