### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by SpencerHorn** [mzbat/iac_workshop#34]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1/GsTruPapf29LdAMCeFZklAimeIN49fyOSk+ZgdEDNABvJsgFA5eY4PRP41onu0a1aY1cIhXj26Jr8GgsrqQCiPa3Nyj800OF0HLpHNuVUHhtm+g6Avhi/z5FuZjw72TOK2roXytSoevl5hEaYxqMtFBKg7KqyWxpfS+JKcdLsoIpuvCEkwpQqbF+GOmPdaAiN0rSsqf40hKAf9gyi85WZ8jJgM9c0QoNsVJoyIuA2qtidevJGWEXx4bWqf08RIclMeoT8NXjiWZcbRceDZlgCqmx2rCaLQLfaxWvD9GeheB4xTMeN0vY2SrLDyEXS6vVtb2N/62gqd77m6yvsYR

**Comment by SpencerHorn** [comment]
username can be shorn if it pleases the gods

**Comment by theDevilsVoice** [comment]
I need the email from the end of this key

**Comment by SpencerHorn** [comment]
spencerhorn@Endure-Unspecified.local

**Comment by theDevilsVoice** [comment]
username shorn
