### ISSUE TITLE
Add my key

### ISSUE THREAD

**Issue by alanbeal** [mzbat/iac_workshop#38]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/jekQTyrYc+4wd+wsFd2Vgepo5pDkopwMYZez0mY2DfRLuq0v3EP9l4H1vQcCPfCz39OHdZWj/INyXFuW5izV32jmbjLk8KUxWaPqjZY7lUslLL4h/2X31dr+Y3fkWJlA3GXjOeSb170nRUNLHVoKtjCKXupOzjHaOwBVh/FXdOABTcvDDurLdbrpZ/5ohbz16+RJNGwNMrxg/tCVRrPMz2455nTvHOmguuS+PEMiyKUEQFfcm0eNfIgVg8fsZwA45Ug/PN+VQOyfBjZBpmX9I/aklVddw2PzJYsXCFXt7CTU/oZZuw1RT1YrLIq1cBXEOEvu84Jvxbx89H3J3wEjs8hitByocWbHltRYgxdWm1w3G2Y8bV0ZXGj3yJWYsvgydMpRYkXq9SnqEaGYI+8x63leoewQeN1dBkar1OtuqAmBKmO91UJUPSyrJOzU3XAkO0amX/tENCKgsUJP6o7C2V7jwjZHJ2Ch9cmVFvmBYyyY7Aa8dBttGd5mipbMtiX3s3Fqi8uFeXN6aF3IOrpUZEoOFtMRUbZ1hUJRMfPiZNFEt6vPsGpgwthL42/FQhgb8A8+OKzA4sNAIPl8+RfYbxtj6oX+HyUiUQwJ5PkDtg3LYBCu37hKcRvUh83OrcpLaPbSpt9FKnZHniJvkSyo26vaNUWNi9y9fkBCXj0gaw== alanbeal@hotmail.com

preferred name alanbeal

**Comment by theDevilsVoice** [comment]
username alanbeal
