### ISSUE TITLE
please add my key

### ISSUE THREAD

**Issue by ken-patton** [mzbat/iac_workshop#45]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYDYeeUGLb+GUKHizMV9XpiOpCkPaZuy8p0a30hl40Mf/t6Ou4qAiJacuzl+v2m10es1UnLT4eclOM0avgElpBj2yZAXGBZ
65IypBPlb7bbGpRALBVHfEmGI5J/UADGFJx+zaGT9Y7YV+Yld1Jz1ORMdAErGMgDfmrBkkK5F19ipXHZo6CT09EYYRTuVtpZ2+D2UhJbDzEjYUvdzPu0x03kAP9E2MSxNsrGf
XenXJApLGDmA9ASvBAhMGYCCSBb9sKxx/4XIeG6nNFl/uQu1dbEzd5ydZf94q0yND+LgUUgtfMqCds4LmHwSRA53waH1UKHFZfyIHMQgmB3LcW93Ri4ZkptsLioqRI49m0OI4
IiugOndO+BEOEOZj3r/Eej3a2Kok9pbylKGqhZOWSRri/mEaEM5A7ZswLv0nuBvWabsulBGruyYsqnIEVPFBa708qjj0hE64ejZnKTJrTxUMOZ23kcc8ENXwJzK/yHBZGU3aV
R9YxUZX1rr4YnthkUw7kI4RtzJPuZoRBjabxM+skODDQVPrlD9jH2puOTdDxlH/YXxgVvUwQJJJ8C4rQxMhxzhSDQJbhBqEM3/pBWFGNrHr1Ll/ZVRN++ewMz79FTB9FgdjrG
H5r3yvgSf2dcI/MvHiEDLHraOOEXmccLyU/jv7To50nbAqfH45Pg8+fKQ== ken@kenpatton.net

**Comment by theDevilsVoice** [comment]
username is ken
