### ISSUE TITLE
Add my key V2

### ISSUE THREAD

**Issue by ascherm97** [mzbat/iac_workshop#50]
username: ascherm97

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcW0kWqtzUwynUf8ksWEjz0fzs/vwbWI+NkcnoOprozpv6anCk9H3z9s3Wiu51Y9G0pAZ7CSebV0fi1AIZGmTRXrR5J1EgqrREo3UgWK3JEeKS3gPdRSgKE+aXmdfYSJONjRbeR/cfebYk7y406IWtWKrywxQUDfg9KUeu0vw4lQkLO69yvxsvhUFucNqT6oynyqYOg41s28VpEuaJEbxQbDy9gT4zIxNLH7/EDJGnb9tPZnMXrfKmeNlmhaT3SwMLfTc48L6PI5jtuudCgGd+9k31Wl5Uqm3oOvfg2UiuoMX55ufNWViF7g4l02ZRX+6I9PCd7jbC6vtaUcxdLJ78ca8PkHaFWgdtwH01+r/hvQAoR7uXWzdsTxVAKMhp0qOaTn6XOySNHyYAl40vODqDZnewahkIvmUDtXz9GJEdwVrE2+hQenJ2oFBklEN0DfbtW5tywj0q+UbjVBMnutDYI56D6Ztf4zE83+Wm4W3o8iMmQyPcDa3OJ8zv1oTZqR4CRNw1qpGOazskF93uryJLmTs+5BDKRk1g/cU3P8he1nAhUHT6Zaq/pz4X4alfO5uTN4wmjMrY8FPlQDhQKQLk/Q/kSAoc23LMH9hnNG9Eh9u8NVbRvym/5jOlxbp0YHIFQq0YpQCtGREbC0I3GUhSfFNGhsILwguMHqcVAUIYGQ== ascherm97@gmail.com

**Comment by theDevilsVoice** [comment]
added
